export const SET_PIZZA_SIZE = "SET_PIZZA_SIZE";
export const SET_PIZZA_CRUST = "SET_PIZZA_CRUST";
export const SET_PIZZA_INGREDIENTS = "SET_PIZZA_INGREDIENTS";

export const SAVE_ORDER = "SAVE_ORDER";
export const RESET_ORDER = "RESET_ORDER";
export const SET_POLL_RESULTS = "SET_POLL_RESULTS";

export const SING_UP = "SING_UP";
export const SING_IN = "SING_IN";
export const SING_OUT = "SING_OUT";
export const AUTHENTICATE = "AUTHENTICATE";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOADING_START = "LOADING_START";
export const LOADING_FINISH = "LOADING_FINISH";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_ORDERS = "FETCH_USER_ORDERS";
export const SAVE_DELIVERY_ADDRESS = "SAVE_DELIVERY_ADDRESS";
export const SAVE_USER_PHOTO = "SAVE_USER_PHOTO";
export const SAVE_USER_DATA_ON_SERVER = "SAVE_USER_DATA_ON_SERVER";
